---
- hosts: localhost
  connection: local
  gather_facts: no
  vars:
    region: us-east-1
  tasks:
    - name: delete DB subnet group
      rds_subnet_group:
        name: dbsg2
        state: absent
        region: "{{ region }}"
