---  
- hosts: localhost  
  gather_facts: no  
  connection: local   
  vars:  
    #your region  
    region: us-east-1    
  tasks:  
    - name: EC2 provisioning with general purpose EBS volume 
      ec2:
        region: "{{ region }}"  
        key_name: ram-key-pair-us-east  
        instance_type: t2.micro  
        image: ami-dc361ebf      
        group: sg_webserver_us-east
        volumes:
          - device_name: /dev/sda1
            device_type: gp2
            volume_size: 100
            delete_on_termination: true
