---  
- hosts: localhost  
  gather_facts: no    
  connection: local 
  tasks:
    - name: create IAM user Ram
      iam:
        iam_type: user
        name: ram
        state: present
        groups: admin
