---  
- hosts: localhost  
  gather_facts: no    
  connection: local 
  tasks:
    - name: Create IAM role app1 for an app 
      iam:
        iam_type: role
        name: app1
        state: present

