- hosts: localhost
  gather_facts: no
  connection: local 
  vars:
    region: us-east-1
  tasks:
    - name: delete mysql RDS instance
      rds:
        command: delete
        region: "{{ region }}"
        instance_name: staging-mysql-1 
