---
- hosts: localhost
  gather_facts: no
  connection: local 
  vars:
    region: us-east-1
    size: 100
    instance_type: db.t3.micro
    db_engine: MySQL
    engine_version: 5.7.37
    subnet: dbsg2 
    parameter_group: mysqlpg1
    # staging_sg_database security group ID
    security_groups: sg-061f55ca92e1778b8
    iops: 1000
    db_name: mydb
    username: dbadmin
    password: mypassword    
  tasks:
    - name: create mysql RDS instance
      rds:
        command: create
        instance_name: staging-mysql-1
        region: "{{ region }}"
        size: "{{ size }}"
        instance_type: "{{ instance_type }}"
        db_engine: "{{ db_engine }}"
        engine_version: "{{ engine_version }}"
        subnet: "{{ subnet }}"
        parameter_group: "{{ parameter_group }}"
        multi_zone: yes
        db_name: "{{ db_name }}"
        username: "{{ username }}"
        password: "{{ password }}"
        vpc_security_groups: "{{ security_groups }}"
        iops: "{{ iops }}"
