---  
- hosts: localhost  
  connection: local  
  gather_facts: no   
  tasks:
    - name: create record 
      route53:
        command: create
        zone: ramkurniawan.com.
        record: ramkurniawan.com.
        type: A
        value: 54.79.34.239

