---
- hosts: localhost
  gather_facts: no
  connection: local 
  vars:
    bucketname: ram001
  tasks:
    - name: create virtual directory
      s3:
        bucket: "{{ bucketname }}"
        object: /backup/database/
        mode: create
