---
- hosts: localhost
  gather_facts: no
  connection: local 
  sudo: yes
  vars:
    bucketname: ram001
  tasks:
    - name: download file
      s3:
        bucket: "{{ bucketname }}"
        object: /backup/database/test.txt
        dest: test.txt
        mode: get
