---
- hosts: localhost
  gather_facts: no
  connection: local 
  vars:
    bucketname: ram001
  tasks:
    - name: share file
      s3:
        bucket: "{{ bucketname }}"
        object: /backup/database/test.txt
        expiration: 3600
        mode: geturl
