---  
- hosts: localhost  
  connection: local  
  gather_facts: no    
  vars_files:
    - staging_vpc_info
  vars:  
    region: us-east-1  
    #your ip address
    allowed_ip: 49.36.179.93/32
    prefix: staging
    vpc_id: "{{ staging_vpc }}"

  tasks:  
    - name: create security group  
      ec2_group:
        region: "{{ region }}"
        name: sg_webserver_us-east    
        vpc_id: "{{ staging_vpc }}"
        description: security group for us-east webserver host
        rules:
          # allow ssh access from your ip address  
          - proto: tcp  
            from_port: 22  
            to_port: 22  
            cidr_ip: "{{ allowed_ip }}"  
          # allow http access from anywhere  
          - proto: tcp  
            from_port: 80    
            to_port: 80    
            cidr_ip: 0.0.0.0/0  
        rules_egress:
          - proto: all
            cidr_ip: 0.0.0.0/0
